// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatbotsController from "./chatbots_controller"
application.register("chatbots", ChatbotsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)
